### ISSUE TITLE
Implement support for IObservable<T>

### ISSUE THREAD

**Issue by jvert** [net-daemon/netdaemon#114]
The current design has a lot of different APIs for subscribing to event streams, filtering them in various ways then performing actions. This needs a lot of documentation, implementation, test, etc and makes things more complex for people trying to figure out how to do stuff.

Reactive Extensions is a standard .NET library for managing asynchronous event-based programming. By supporting this natively netdaemon could leverage the existing library and documentation and not have to reimplement the basic functionality. More info can be found at https://github.com/dotnet/reactive, http://introtorx.com/ and http://reactivex.io/

## Additional context
The current Fluent API IStateChanged interface has multiple overloads of WhenStateChange.
```
Entity("binary_sensor.my_motion_sensor").WhenStateChange(to: "on").UseEntity("light.light1").TurnOn().Execute();
Entity("binary_sensor.my_motion_sensor").WhenStateChange(from: "off", to:"on").UseEntity("light.light1").TurnOn().Execute();
Entity("binary_sensor.my_motion_sensor").WhenStateChange((toState, fromState) => toState?.State == "on").UseEntity("light.light1").TurnOn().Execute();
Entity("sun.sun")
    .WhenStateChange((n, o) =>
        n?.Attribute?.elevation <= 3.0 &&
        n?.Attribute?.rising == false &&
        o?.Attribute?.elevation >  3.0).UseEntity("light.light1").TurnOn().Execute();
```
Using RX these can all just be replaced by a standard LINQ Where() filter. For example, if IEntity implemented `IObservable<EntityState>` then you can do something like this
```
Entity("binary_sensor.my_motion_sensor")
    .Where(state => state.State == "on")
    .ForEach(e => Entity("light.light1").TurnOn());
```
For the case where your logic needs the previous state, the current API has a WhenStateChange overload that provides it as toState and fromState. With RX that is not required as you can use the standard RX APIs to create whatever kind of event stream you need:
```
Entity("binary_sensor.my_motion_sensor")
    .Scan((default(EntityState),default(EntityState)), (last, current) => (last.Item2, current))
    .Where(t => t.Item2.State == "on")
    .ForEach(e => Entity("light.light1").TurnOn());
```
Here the Scan() operator is turning our IObservable<EntityState> event stream into a `IObservable<(EntityState,EntityState)>` event stream, where each event is a tuple (from, to). There is no special code required in netdaemon to handle the previous state (although you could provide some convenience wrapper if it was a common usage). If I wanted a rolling average or the last 5 measurements or debouncing, I can build that directly.

Let's consider a more complicated (but realistic!) example. I have a light that I want on from sunset until 10pm, but only when I am home.
```
var sunset = Entity("sun.sun").Where(s => s.State == "Below horizon").Select(s => true);
var tenpm = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.Today.Day, 22, 0, 0);
var bedtime = Observable.Timer(new DateTimeOffset(tenpm), TimeSpan.FromDays(1)).Select(s => false);
var imhome = Entity("person.john").Where(s => s.State == "home").Select(s => true);
```
Now we have created three different IObservable<bool> event streams. sunset emits TRUE at sunset. bedtime emits FALSE at 10pm. And imhome emits TRUE or FALSE depending on my presence. Now we just have to combine them to get the state we want the light to be in.
```
sunset.Concat(bedtime)
    .CombineLatest(imhome, (time, home) => time && home)
    .ForEach(turnon => {
        if (b) {
            Entity("light.light1").TurnOn());
        } else {
            Entity("light.light1").TurnOff());
        }
    };
```
Again you can see that once these event streams exist they can easily be combined in interesting ways without having to add any additional code to netdaemon. There might be some convenient wrappers for common patterns, but the underlying plumbing is all done by RX.

**Comment by helto4real** [comment]
This is a very interesting proposition. We need a story for the async model. I am keen on keep this product "async only" cause I think it will benefit long term resource friendly I/O. Since todays interface has Entity as a selector to do actions on... In your case it would be "States" that should be used I guess. 

```c#
Entity("light.light1").TurnOn().ExecuteAsync();
```
The reason I used the "ExecuteAsync()" fluent API is that I wanted chained calls. With this the chains can be done with Rx instead. Maybee we should create a whole new interface:
Rx.Entity(""), but here we need to be careful that Entity means the same thing... 
Rx.States("xyz") would be more in line with how current API is designed. 

Now to the real question. Do we want to design the API to makes sense in a Rx world and break the current or do we keep two alternatives? Long term I would say we should focus on one model and this will break existing. But if we would do a major change it is better to do it now before too many users. 

So my suggestion is to implement a "Rx" property where we do all Rx related API:s (unless it can be used in the current API too.. We get a feel for it and then decide it this should be the default and we keep the old one as a deprecated legacy (funny to say for a 4 month old product.) so we give people a way to adapt.
