### ISSUE TITLE
web api hardcoded to port 5000

### ISSUE THREAD

**Issue by jvert** [net-daemon/netdaemon#176]
PROBLEM: The new web API controller is hardcoded to run on port 5000. And the new admin UI is hardcoded to http://127.0.0.1:5000/api/apps. Unfortunately this conflicts with my configuration (running in a docker container on my Synology NAS which already has the admin UI on port 5000)

SOLUTION: Allow overriding the port via env variable like the rest of the configuration. e.g. NETDAEMON__WEBAPIPORT=5001

## 

Happy to put together a PR if you want it

**Comment by helto4real** [comment]
yea will fix this...

**Comment by ludeeus** [comment]
@jvert This should only be an issue if you run the container on the host network, which you should not do.

If you want access to the Admin UI, you should add a port map for the internal :1337 port, as shown in the documentation instead of running it on the host network.

https://netdaemon.xyz/docs/started/installation#example-docker-run-configuration

**Comment by helto4real** [comment]
it is fixed in dev and will be available in next release
